FROM microsoft/dotnet:2.0-sdk AS build-env

RUN apt-get update && apt-get install -y --no-install-recommends poppler-utils \
    libgdiplus

WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out
RUN dotnet test UnitTests/UnitTests.csproj

FROM microsoft/dotnet:2.0-runtime

RUN apt-get update && apt-get install -y --no-install-recommends poppler-utils \
    libgdiplus

WORKDIR /app

COPY --from=build-env /app/out ./

EXPOSE 5050

ENTRYPOINT ["dotnet", "PDF2PNG.dll"]
